version: '3.7'

services:
  arangodb:
    image: arangodb/arangodb:3.10
    volumes:
      - arangodb:/var/lib/arangodb3
      - arango-apps:/var/lib/arangodb3-apps
    environment:
      ARANGO_ROOT_PASSWORD: Ohng0Ior
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 8529:8529

volumes:
  arangodb:
  arango-apps: