version: '3.3'

services:
  arangodb:
    image: arangodb/arangodb:3.10.1
    volumes:
      - arangodb:/var/lib/arangodb3
      - arango-apps:/var/lib/arangodb3-apps
    environment:
      - ARANGO_ROOT_PASSWORD_FILE=/run/secrets/arangodb_root_password
    secrets:
      - arangodb_root_password
    networks:
      - arangodb
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 8529:8529

volumes:
  arangodb:
  arango-apps:

networks:
  arangodb:

secrets:
  arangodb_root_password:
    external: true