version: '3.8'

services:
  redis:
    image: redis:7.0.9
    volumes:
      - redis-data:/data
    networks:
      - redis-net
      - TASTEST
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  redis-net:
  TASTEST:
    external: true

volumes:
  redis-data:
