version: '3.7'

services:
  tas-front:
    image: benkockyo/tas:latest
    volumes:
      - /var/lib/docker/volumes/tasjs/tas.js:/srv/tas/tas-front/config/tas.js
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 8000:8000
  tas-back:
    image: benkockyo/tas:back
    restart: always
    volumes:
        - /var/lib/docker/volumes/localjs/local.js:/srv/tas/tas-back/config/local.js
    ports:
        - "8001:8001"
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    volumes:
        - database:/var/opt/mssql
    ports:
        - 1433:1433
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Docker1221@
        - MSSQL_PID=Developer


volumes:
  database: