name: Check and Install Python
on: push
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Check Python
      run: |
        if ! command -v python3 &> /dev/null
        then
            echo "Python could not be found. Installing..."
            sudo yum install -y python3
        fi
