name: Trigger test

on:
  repository_dispatch:
    types: [trigger-test-event]

jobs:
  trigger-test:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Run test
        run: docker run ubuntu:latest ls -la
