name: Trigger test

on:
  pull_request:
  workflow_dispatch:


jobs:
  trigger-test:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Run test
        run: docker run localhost:5000/ubuntu:latest ls -la